// Generated by CoffeeScript 1.6.3
(function() {
  var should, xls2json;

  should = require("should");

  xls2json = require("./xls2json");

  describe("xls should been converted", function() {
    return it("should success", function(done) {
      var json;
      json = xls2json.make_dynamic_json("bookshop.xls", "category");
      console.log("===================");
      console.dir(json);
      json.should.be.json;
      return done();
    });
  });

}).call(this);
